#!/bin/sh
use(){ for p in "$@"; do [ -x "mod/$p" ] || continue; . "./mod/$p"; done }
log(){ [ "$quiet" != '1' ] && printf '\e[0;%sm[\e[0m%s\e[0;%sm]\e[0m %s\n' "${3:-35}" "${2:-info}" "${3:-35}" "$1"; }
warn(){ log "$1" "${2:-warning}" 33; }
err(){ log "$1" "${2:-error}" 31; exit 1; }
run(){
        [ -z "$1" ] && err 'missing args'
        find 'src' -type f -path "*/${2:-*}/$1" | while read -r in
        do
                dir="${in%/*}"
                if [ -x "$in" ]; then
                        log "${dir##*/} $1" 'run'
                        . "./$in"
                fi
        done
}

cd "$(dirname "$(realpath "$0")")" || exit
[ -x 'config' ] && . './config'
run "$1" "$2"
